name: MARVEL

on:
  push:
    branches: [ main ]
    
jobs:
  bestHero:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Ironman
  avengers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Spiderman, Hulk, Captain America, Black Widow, 
